<?php

/** @var Algolia_Algoliasearch_Helper_Config $config */
$config = Mage::helper('algoliasearch/config');

/** @var Mage_Customer_Model_Session $session */
$session = Mage::getSingleton('customer/session');
$customerGroupId = $session->getCustomerGroupId();

$storeId = Mage::app()->getStore()->getStoreId();
$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();

$priceKey = '.'.$currencyCode.'.default';
if ($config->isCustomerGroupsEnabled($storeId)) {
    $priceKey = '.'.$currencyCode.'.group_'.$customerGroupId;
}

?>

<!-- Product hit template -->
<script type="text/template" id="autocomplete_products_template">
    <a class="algoliasearch-autocomplete-hit"
        {{^__queryID}} href="{{url}}" {{/__queryID}}
        {{#__queryID}} href="{{urlForInsights}}" {{/__queryID}}
        data-objectid="{{objectID}}"
        data-position="{{__position}}"
        data-queryid="{{__queryID}}"
    >
        {{#thumbnail_url}}
            <div class="thumb"><img src="{{thumbnail_url}}" /></div>
        {{/thumbnail_url}}

        <div class="info">
            {{{_highlightResult.name.value}}}

            <div class="algoliasearch-autocomplete-category">
                {{#categories_without_path}}
                    <?php echo $this->__('in'); ?>
                    {{{categories_without_path}}}
                {{/categories_without_path}}

                {{#_highlightResult.color}}
                    {{#_highlightResult.color.value}}
                        <span>
                           {{#categories_without_path}} | {{/categories_without_path}} Color:  {{{_highlightResult.color.value}}}
                        </span>
                    {{/_highlightResult.color.value}}
                {{/_highlightResult.color}}
            </div>

            <div class="algoliasearch-autocomplete-price">
                <span class="after_special {{#price<?php echo $priceKey; ?>_original_formated}}promotion{{/price<?php echo $priceKey; ?>_original_formated}}">
                    {{price<?php echo $priceKey; ?>_formated}}
                </span>

                {{#price<?php echo $priceKey; ?>_original_formated}}
                    <span class="before_special">
                        {{price<?php echo $priceKey; ?>_original_formated}}
                    </span>
                {{/price<?php echo $priceKey; ?>_original_formated}}
            </div>
        </div>
    </a>
</script>