<?php /** @var $this Algolia_Algoliasearch_Block_Adminhtml_IndexingQueue_Status */ ?>
<div class="message notice-msg algolia-notice">
    <div id="messages-message-notice">
        <p>
            <?php echo $this->__('Status of the queue: <strong>%s</strong>', $this->getQueueRunnerStatus()); ?><br/>
            <?php if ($this->getLastQueueUpdate()): ?>
                <?php echo $this->__('Last update: <strong>%s</strong>', $this->getLastQueueUpdate()); ?>
            <?php endif ?>
        </p>
        <?php $notices = $this->getNotices() ?>
        <?php foreach ($notices as $notice) : ?>
            <p><?php echo $notice ?></p>
        <?php endforeach; ?>
    </div>
</div>