FROM algolia/base-algoliasearch-magento

# Enable XDebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

# test script
COPY ./bin/test.sh /usr/local/bin/test.sh
RUN chmod +x /usr/local/bin/test.sh

# GO
ENTRYPOINT test.sh
