<!-- Product hit template -->
<script type="text/template" id="instant-hit-template">
    <div class="col-md-4 col-sm-6">
        <div class="result-wrapper">
            <a href="{{url}}" class="result">
                <div class="result-content">
                    <div class="result-thumbnail">
                        {{#image_url}}<img src="{{{ algoliaConfig.baseUrl }}}/{{{ image_url }}}"/>{{/image_url}}
                        {{^image_url}}<span class="no-image"></span>{{/image_url}}
                    </div>
                    <div class="result-sub-content">
                        <h3 class="result-title text-ellipsis">
                            {{{ _highlightResult.name.value }}}
                        </h3>
                        <div class="ratings">
                            <div class="ratings-wrapper">
                                <div class="ratings-sub-content">
                                    <div class="rating-box">
                                        <div class="rating" style="width:{{rating_summary}}%" width="148"
                                             height="148"></div>
                                    </div>
                                </div>
                                <div class="price">
                                    <div class="price-wrapper">
                                        <div>
                                            <span
                                                class="after_special {{#original_formatted_price}}promotion{{/original_formatted_price}}">
                                                {{formatted_price}}
                                            </span>

                                            {{#original_formatted_price}}
                                                <span class="before_special">
                                                    {{original_formatted_price}}
                                                </span>
                                            {{/original_formatted_price}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="result-description text-ellipsis">{{{ _highlightResult.description.value }}}</div>

                        {{#isAddToCartEnabled}}
                        {{#in_stock}}
                        <form action="{{{ algoliaCofig.baseUrl }}}/checkout/cart/add/product/{{ objectID }}"
                              method="post">
                            <input type="hidden" name="form_key"
                                   value="{{{ algoliaConfig.request.formKey }}}"/>
                            <input type="hidden" name="qty" value="1">
                            <button type="submit">{{{ algoliaConfig.translations.addToCart }}}</button>
                        </form>
                        {{/in_stock}}
                        {{/isAddToCartEnabled}}
                    </div>
                </div>
                <div class="clearfix"></div>
            </a>
        </div>
    </div>
</script>