<!-- Search statistics template (used for displaying hits' count and time of query) -->
<script type="text/template" id="instant-stats-template">
    {{#hasOneResult}}
        <strong>1</strong>
        {{ translations.result }}
        {{ translations.found }}
    {{/hasOneResult}}

    {{#hasManyResults}}
        {{^hasNoResults}}
            {{first}}-{{last}} {{ translations.outOf }}
        {{/hasNoResults}}

        <strong>{{#helpers.formatNumber}}{{nbHits}}{{/helpers.formatNumber}} {{ translations.resultsFound }}</strong>
    {{/hasManyResults}}

    {{ translations.in }} {{seconds}} {{ translations.seconds }}
</script>