<?php

/** @var Algolia_Algoliasearch_Block_Adminhtml_Notifications $this */

$queueInfo = $this->getQueueInfo();

?>

<div class="notification-global algoliasearch-queue-notification"> <!-- TODO FIX the SKIN URL -->
    <strong>Algolia Search</strong> -
    <?php if($queueInfo['isEnabled'] === true):?>
        <strong>
            <a href="<?php echo $this->getConfigurationUrl(); ?>">Indexing queue</a> information:
        </strong>

        Number of queued jobs: <strong><?php echo $queueInfo['currentSize']; ?></strong>,

        <?php if ($queueInfo['currentSize'] > 0): ?>
            all queued jobs will be processed in appr. <strong><?php echo $queueInfo['eta']; ?></strong>,
        <?php endif; ?>

        more information about how the indexing queue works you can find in the documentation: <a href="https://community.algolia.com/magento/doc/m1/indexing/?utm_source=magento&utm_medium=extension&utm_campaign=magento_1&utm_term=shop-owner&utm_content=doc-link#general-information" target="_blank">Indexing queue</a>
    <?php else: ?>
        <strong>
            <a href="<?php echo $this->getConfigurationUrl(); ?>">Indexing queue</a> is not enabled.
        </strong>

        It's highly recommended to enable it, especially if you are on production environment. You can learn how to enable the index queue in the documentation: <a href="https://community.algolia.com/magento/doc/m1/indexing/?utm_source=magento&utm_medium=extension&utm_campaign=magento_1&utm_term=shop-owner&utm_content=doc-link#general-information" target="_blank">Indexing queue</a>
    <?php endif; ?>
</div>
