<!-- General autocomplete menu template -->
<script type="text/template" id="menu-template">
    <div class="autocomplete-wrapper">
        <div class="col9">
            <div class="aa-dataset-products"></div>
        </div>
        <div class="col3">
            <div class="other-sections">
                <div class="aa-dataset-suggestions"></div>
                <div class="aa-dataset-0"></div>
                <div class="aa-dataset-1"></div>
                <div class="aa-dataset-2"></div>
                <div class="aa-dataset-3"></div>
                <div class="aa-dataset-4"></div>
                <div class="aa-dataset-5"></div>
                <div class="aa-dataset-6"></div>
                <div class="aa-dataset-7"></div>
                <div class="aa-dataset-8"></div>
                <div class="aa-dataset-9"></div>
            </div>
        </div>
    </div>
</script>