<!-- Product hit template -->
<script type="text/template" id="autocomplete_products_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        {{#thumbnail_url}}
        <div class="thumb"><img src="{{{ baseUrl }}}/{{ thumbnail_url }}" /></div>
        {{/thumbnail_url}}

        <div class="info">
            {{{_highlightResult.name.value}}}

            <div class="algoliasearch-autocomplete-category">
                {{#categories_without_path}}
                {{ inTranslation }} {{{categories_without_path}}}
                {{/categories_without_path}}

                {{#_highlightResult.color}}
                {{#_highlightResult.color.value}}
                <span>
                   {{#categories_without_path}} | {{/categories_without_path}} Color:  {{{_highlightResult.color.value}}}
                </span>
                {{/_highlightResult.color.value}}
                {{/_highlightResult.color}}
            </div>

            <div class="algoliasearch-autocomplete-price">
                    <span class="after_special {{#original_formatted_price}}promotion{{/original_formatted_price}}">
                        {{formatted_price}}
                    </span>

                {{#original_formatted_price}}
                    <span class="before_special">
                        {{original_formatted_price}}
                    </span>
                {{/original_formatted_price}}
            </div>
        </div>
    </a>
</script>