<?php /** @var $this Algolia_Algoliasearch_Block_Adminhtml_Algoliasearchbackend */ ?>
<div class="content-header">
    <h3><?php echo $this->__('Algolia Search Administration') ?></h3>
</div>

<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="fieldset-legend"><?php echo $this->__('Credentials') ?></h4></div>
    <div class="fieldset">
        <ul>
            <li><strong><?php echo $this->__('APPLICATION_ID:') ?></strong> <?php echo $this->getApplicationId() ?></li>
        </ul>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="fieldset-legend"><?php echo $this->__('Statistics') ?></h4></div>
    <div class="fieldset">
        <p><?php echo $this->__('Access to your Algolia dashboard:') ?> <a target="_blank" href="https://www.algolia.com/dashboard">www.algolia.com/dashboard</a></p>
        <ul>
            <li><strong><?php echo $this->__('Indexed Entities:') ?></strong> <?php echo $this->getNbEntitiesIndexed() ?></li>
        </ul>
    </div>
</div>

<div class="content-header">
    <h3><?php echo $this->__('Reindex your catalog') ?></h3>
</div>

<p><?php echo $this->__('To reindex the whole content of your catalog, please click on the following link:') ?></p>

<form id="reindex-form" name="reindex-form" method="post" action="<?php echo $this->getUrl('*/*/reindex/') ?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <button type='button' onclick="reindexForm.submit()">
        <span><?php echo $this->__('Reindex') ?></span>
    </button>
</form>

<script type="text/javascript">
    //<![CDATA[
    var reindexForm = new varienForm('reindex-form', false);
    //]]>
</script>
