<div class="content-header">
  <h3>Algolia Search Administration</h3>
</div>

<div class="entry-edit">
  <div class="entry-edit-head"><h4 class="fieldset-legend">Credentials</h4></div>
  <div class="fieldset">
    <ul>
      <li><strong>APPLICATION_ID:</strong> <?php echo $this->getApplicationId() ?></li>
    </ul>
  </div>
</div>

<div class="entry-edit">
  <div class="entry-edit-head"><h4 class="fieldset-legend">Statistics</h4></div>
  <div class="fieldset">
    <p>Access to your Algolia dashboard: <a href="https://www.algolia.com/dashboard">www.algolia.com/dashboard</a></p>

    <ul>
      <li><strong>Indexed Products:</strong> <?php echo $this->getNbProductsIndexed() ?></li>
      <li><strong>Indexed Categories:</strong> <?php echo $this->getNbCategoriesIndexed() ?></li>
    </ul>
  </div>
</div>

<div class="content-header">
  <h3>Reindex your catalog</h3>
</div>

<p>To reindex the whole content of your catalog, please click on the following link:</p>

<form id="reindex-form" name="reindex-form" method="post" action="<?php echo $this->getUrl('*/*/reindex/') ?>">
  <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
  <button type='button' onclick="reindexForm.submit()">
    <span>Reindex</span>
  </button>
</form>

<script type="text/javascript">
  //<![CDATA[
  var reindexForm = new varienForm('reindex-form', false);
  //]]>
</script>