<?php

/** @var Algolia_Algoliasearch_Helper_Config $config */
$config = Mage::helper('algoliasearch/config');

/** @var Mage_CatalogSearch_Helper_Data $catalogSearchHelper */
$catalogSearchHelper = $this->helper('catalogsearch');

$placeholder = $this->__('Search for products, categories, ...');

/** Render form with autocomplete input **/
if ($config->isDefaultSelector()): ?>
    <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
        <div id="algolia-searchbox">
            <label for="search"><?php echo $this->__('Search:') ?></label>
            <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" class="input-text algolia-search-input" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" placeholder="<?php echo $placeholder; ?>" />
            <img class="clear-query-autocomplete" src="<?php echo $this->getSkinUrl('algoliasearch/cross.png') ?>" />
            <svg id="algolia-glass" xmlns="http://www.w3.org/2000/svg" class="magnifying-glass" width="24" height="24" viewBox="0 0 128 128" >
                <g transform="scale(4)">
                    <path stroke-width="3" d="M19.5 19.582l9.438 9.438"></path>
                    <circle stroke-width="3" cx="12" cy="12" r="10.5" fill="none"></circle>
                    <path d="M23.646 20.354l-3.293 3.293c-.195.195-.195.512 0 .707l7.293 7.293c.195.195.512.195.707 0l3.293-3.293c.195-.195.195-.512 0-.707l-7.293-7.293c-.195-.195-.512-.195-.707 0z" ></path>
                </g>
            </svg>
        </div>
    </form>
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[

    document.addEventListener("DOMContentLoaded", function(event) {
        algoliaBundle.$(function ($) {

            /** We have nothing to do here if autocomplete is disabled **/
            if (!algoliaConfig.autocomplete.enabled) {
                return;
            }

            /**
             * Set autocomplete templates
             * For templating is used Hogan library
             * Docs: http://twitter.github.io/hogan.js/
             **/
            algoliaConfig.autocomplete.templates = {
                suggestions: algoliaBundle.Hogan.compile($('#autocomplete_suggestions_template').html()),
                products: algoliaBundle.Hogan.compile($('#autocomplete_products_template').html()),
                categories: algoliaBundle.Hogan.compile($('#autocomplete_categories_template').html()),
                pages: algoliaBundle.Hogan.compile($('#autocomplete_pages_template').html()),
                additionnalSection: algoliaBundle.Hogan.compile($('#autocomplete_extra_template').html())
            };

            /**
             * Initialise Algolia client
             * Docs: https://www.algolia.com/doc/javascript
             **/
            var algolia_client = algoliaBundle.algoliasearch(algoliaConfig.applicationId, algoliaConfig.apiKey);
            algolia_client.addAlgoliaAgent('Magento ' + algoliaConfig.extensionVersion);

            /** Add products and categories that are required sections **/
            var nb_cat = algoliaConfig.autocomplete.nbOfCategoriesSuggestions >= 1 ? algoliaConfig.autocomplete.nbOfCategoriesSuggestions : 2;
            var nb_pro = algoliaConfig.autocomplete.nbOfProductsSuggestions >= 1 ? algoliaConfig.autocomplete.nbOfProductsSuggestions : 6;
            var nb_que = algoliaConfig.autocomplete.nbOfQueriesSuggestions >= 0 ? algoliaConfig.autocomplete.nbOfQueriesSuggestions : 0;

            if (nb_que > 0) {
                algoliaConfig.autocomplete.sections.unshift({ hitsPerPage: nb_que, label: '', name: "suggestions"});
            }

            algoliaConfig.autocomplete.sections.unshift({ hitsPerPage: nb_cat, label: <?php echo json_encode($this->__('Categories')); ?>, name: "categories"});
            algoliaConfig.autocomplete.sections.unshift({ hitsPerPage: nb_pro, label: <?php echo json_encode($this->__('Products')); ?>, name: "products"});

            /** Setup autocomplete data sources **/
            var sources = [],
                i = 0;
            $.each(algoliaConfig.autocomplete.sections, function (name, section) {
                var source = getAutocompleteSource(section, algolia_client, $, i);

                if (source) {
                    sources.push(source);
                }

                /** Those sections have already specific placeholder, so do not use the default aa-dataset-{i} class **/
                if (section.name !== 'suggestions' && section.name !== 'products') {
                    i++;
                }
            });

            /**
             * Setup the autocomplete search input
             * For autocomplete feature is used Algolia's autocomplete.js library
             * Docs: https://github.com/algolia/autocomplete.js
             **/
            $(algoliaConfig.autocomplete.selector).each(function (i) {
                var menu = $(this);
                var options = {
                    hint: false,
                    templates: {
                        dropdownMenu: '#menu-template'
                    },
                    dropdownMenuContainer: "#algolia-autocomplete-container",
                    debug: false
                };

                if (algoliaConfig.removeBranding === false) {
                    options.templates.footer = '<div class="footer_algolia"><span><?php echo $this->__('Search by'); ?></span> <a href="https://www.algolia.com/?utm_source=magento&utm_medium=link&utm_campaign=magento_autocompletion_menu" target="_blank"><img src="<?php echo $this->getSkinUrl('algoliasearch/algolia-logo.png'); ?>" /></a></div>';
                }

                /** Bind autocomplete feature to the input */
                $(this)
                    .autocomplete(options, sources)
                    .parent()
                    .attr('id', 'algolia-autocomplete-tt')
                    .on('autocomplete:updated', function (e) {
                        fixAutocompleteCssSticky(menu);
                    })
                    .on('autocomplete:updated', function (e) {
                        fixAutocompleteCssHeight(menu);
                    });

                $(window).resize(function () {
                    fixAutocompleteCssSticky(menu);
                });
            });
        });
    });

    //]]>
</script>