<?php
    $catalogSearchHelper = $this->helper('catalogsearch'); /** @var $catalogSearchHelper Mage_CatalogSearch_Helper_Data */
    $algoliaSearchHelper = $this->helper('algoliasearch'); /** @var $algoliaSearchHelper Algolia_Algoliasearch_Helper_Data */
?>


<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="algoliasearch-autocomplete">
            <div id="search_autocomplete_categories"></div>
            <div id="search_autocomplete_products"></div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var algoliaLiveSearch = new AlgoliaLiveSearch({
    placeholder: '<?php echo $this->__('Search entire store here...') ?>',
    applicationID: '<?php echo $algoliaSearchHelper->getApplicationID() ?>',
    apiKey: '<?php echo $algoliaSearchHelper->getSearchOnlyAPIKey() ?>',
    indexName: '<?php echo $algoliaSearchHelper->getIndexName() ?>',
    searchDelay: <?php echo (int) $algoliaSearchHelper->getSearchDelay() ?>,
    minLength: <?php echo (int) $algoliaSearchHelper->getMinimalQueryLength() ?>,
    queryOptions: {
        hitsPerPage: <?php echo (int) $algoliaSearchHelper->getNbSuggestions() ?>,
        tagFilters: '(product,category)',
        attributesToRetrieve: <?php echo json_encode($algoliaSearchHelper->getAttributesToRetrieve()) ?>,
        attributesToHighlight: 'name'
    },
    renderResults: function (results) {
        if ( ! results.hits) {
            return;
        }

        // Prepare products and categories data
        var hits = results.hits,
            nbSuggestions = this.options.queryOptions.hitsPerPage,
            products = [],
            categories = [],
            html, i;
        hits.each(function(hit) {
            if (typeof(hit) === 'object' && typeof(hit._tags) === 'object') {
                if (hit._tags.indexOf('product') > -1) {
                    products.push(hit);
                } else if (hit._tags.indexOf('category') > -1) {
                    categories.push(hit);
                }
            }
        });
        var displayCategories = (categories.length > 0);
        var displayProducts = (products.length > 0) || (categories.length < nbSuggestions);

        // Display categories
        if (displayCategories) {
            html = '<div class="algoliasearch-autocomplete-title"><?php echo $this->__('Categories') ?></div>';
            for (i = 0; i < categories.length; ++i) {
                hit = categories[i];
                html += '<a class="algoliasearch-autocomplete-hit" href="' + hit.url + '">' +
                    (hit.image_url ? '<div class="thumb"><img src="' + hit.image_url + '" /></div>' : '') +
                    '<div class="info">' +
                    hit._highlightResult.name.value +
                    <?php if ($algoliaSearchHelper->isIndexProductCount()): ?>
                    ' <small>(' + hit.product_count + ')</small>' +
                    <?php endif ?>
                    '</div>' +
                    '<div class="clearfix"></div>' +
                    '</a>';
            }
            $('search_autocomplete_categories').update(html);
        }

        // Display products
        if (displayProducts) {
            html = '<div class="algoliasearch-autocomplete-title"><?php echo $this->__('Products') ?></div>';
            if (products.length > 0) {
                for (i = 0; i < products.length; ++i) {
                    var hit = products[i];
                    html += '<a class="algoliasearch-autocomplete-hit" href="' + hit.url + '">' +
                        (hit.thumbnail_url ? '<div class="thumb"><img src="' + hit.thumbnail_url + '" /></div>' : '') +
                        '<div class="info">' +
                        hit._highlightResult.name.value +
                        (hit.categories && hit.categories.length > 0 ? '<div class="algoliasearch-autocomplete-category">in ' + hit.categories.join(', ') + '</div>' : '') +
                        '</div>' +
                        '<div class="clearfix"></div>' +
                        '</a>';
                }
            } else {
                html += '<div><?php echo $this->__('No results.') ?></div>'
            }
            $('search_autocomplete_products').update(html);
        }
        $('search_autocomplete').select('a').invoke('observe', 'click', function(e){
            var searchQuery = algoliaLiveSearch.searchForm.field.getValue();
            if(searchQuery){
                Mage.Cookies.set('lastSearchQuery', searchQuery);
            }
        });
    },
    clearResults: function() {
        $('search_autocomplete_categories').update('');
        $('search_autocomplete_products').update('');
    }
});
//]]>
</script>
